name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore RozeCare.sln
      - name: Build
        run: dotnet build RozeCare.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test RozeCare.sln --no-build --configuration Release

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm
          cache-dependency-path: web/roze-pwa/package-lock.json
      - name: Install
        working-directory: web/roze-pwa
        run: npm install
      - name: Test
        working-directory: web/roze-pwa
        run: npm run test -- --run
      - name: Build
        working-directory: web/roze-pwa
        run: npm run build

  docker:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/RozeCare.Api/Dockerfile
          tags: ghcr.io/example/roze-api:latest
          push: false
      - name: Build PWA image
        uses: docker/build-push-action@v5
        with:
          context: web/roze-pwa
          file: web/roze-pwa/Dockerfile
          tags: ghcr.io/example/roze-pwa:latest
          push: false
